version: 0.2
phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - CI=true
      - echo Running unit tests
      - npm run test
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./build/ s3://${deploymentBucket}/ --delete
      - aws cloudfront create-invalidation --distribution-id ${distributionId} --paths /*
artifacts:
  files:
    - '**/*'
  base-directory: build